export default {
    "001": {
        "name": "thundershock",
        "type": "electric",
        "cost": 1,
        "target": true,
        "draw": 0,
        "damage": 6,
        "damageTimes": 1,
        "damageAOE": false,
        "block": 0,
        "ignoreBlock": false,
        "energy": 0,
    },


    "002": {
        "name": "discharge",
        "type": "electric",
        "cost": 1,
        "target": false,
        "draw": 0,
        "damage": 3,
        "damageTimes": 1,
        "damageAOE": true,
        "block": 0,
        "ignoreBlock": false,
        "energy": 0,
    },

    "003": {
        "name": "agility",
        "type": "psychic",
        "cost": 0,
        "target": false,
        "draw": 2,
        "damage": 0,
        "damageTimes": 0,
        "damageAOE": false,
        "block": 0,
        "ignoreBlock": false,
        "energy": 0,
    },

    "004": {
        "name": "protect",
        "type": "normal",
        "cost": 1,
        "target": false,
        "draw": 0,
        "damage": 0,
        "damageTimes": 0,
        "damageAOE": false,
        "block": 5,
        "ignoreBlock": false,
        "energy": 0,
    },

    "005": {
        "name": "focus energy",
        "type": "normal",
        "cost": 1,
        "target": false,
        "draw": 0,
        "damage": 0,
        "damageTimes": 0,
        "damageAOE": false,
        "block": 0,
        "ignoreBlock": false,
        "energy": 2,
    },
}