export default {
    "001": {
        "name": "thundershock",
        "type": "electric",
        "category": "attack",
        "rarity": "common",
        "cost": 1,
        "target": true,
        "draw": 0,
        "damage": 6,
        "damageTimes": 1,
        "damageAOE": false,
        "block": 0,
        "ignoreBlock": false,
        "energy": 0,
        "tooltip": 'Deal <span class="damage">§</span> damage to an ennemy',
    },


    "002": {
        "name": "discharge",
        "type": "electric",
        "category": "attack",
        "rarity": "medium",
        "cost": 1,
        "target": false,
        "draw": 0,
        "damage": 3,
        "damageTimes": 1,
        "damageAOE": true,
        "block": 0,
        "ignoreBlock": false,
        "energy": 0,
        "tooltip": 'Deal § damage to all ennemies',
    },

    "003": {
        "name": "agility",
        "type": "psychic",
        "category": "ability",
        "rarity": "medium",
        "cost": 0,
        "target": false,
        "draw": 2,
        "damage": 0,
        "damageTimes": 0,
        "damageAOE": false,
        "block": 0,
        "ignoreBlock": false,
        "energy": 0,
        "tooltip": 'Draw 2 cards',
    },

    "004": {
        "name": "protect",
        "type": "normal",
        "category": "ability",
        "rarity": "common",
        "cost": 1,
        "target": false,
        "draw": 0,
        "damage": 0,
        "damageTimes": 0,
        "damageAOE": false,
        "block": 5,
        "ignoreBlock": false,
        "energy": 0,
        "tooltip": 'Gain 5 block',
    },

    "005": {
        "name": "focus energy",
        "type": "normal",
        "category": "ability",
        "rarity": "rare",
        "cost": 1,
        "target": false,
        "draw": 0,
        "damage": 0,
        "damageTimes": 0,
        "damageAOE": false,
        "block": 0,
        "ignoreBlock": false,
        "energy": 2,
        "tooltip": 'Gain 2 energy',
    },
}