export default {
    "001": {
        "name": "thundershock",
        "type": "electric",
        "category": "attack",
        "rarity": "common",
        "cost": 1,
        "target": true,
        "damageTimes": 1,
        "effect": {
            "draw": 0,
            "damage": 6,
            "selfDamage": 0,
            "damageAOE": false,
            "block": 0,
            "ignoreBlock": false,
            "energy": 0,
            "buffSelfAttack": -1,
            "buffSelfDefense": -1,
            "debuffAttack": 2,
        },
        "tooltip": 'Deal <span class="damage-amount">§</span> damage to an ennemy',
    },


    "002": {
        "name": "discharge",
        "type": "electric",
        "category": "attack",
        "rarity": "medium",
        "cost": 1,
        "target": false,
        "damageTimes": 1,
        "effect": {
            "draw": 0,
            "damage": 3,
            "damageAOE": true,
            "block": 0,
            "ignoreBlock": false,
            "energy": 0,
        },
        "tooltip": 'Deal § damage to all ennemies',
    },

    "003": {
        "name": "agility",
        "type": "psychic",
        "category": "ability",
        "rarity": "medium",
        "cost": 0,
        "target": false,
        "effect": {
            "draw": 2,
            "damage": 0,
            "damageAOE": false,
            "block": 0,
            "ignoreBlock": false,
            "energy": 0,
        },
        "tooltip": 'Draw 2 cards',
    },

    "004": {
        "name": "protect",
        "type": "normal",
        "category": "ability",
        "rarity": "common",
        "cost": 1,
        "target": false,
        "effect": {
            "draw": 0,
            "damage": 0,
            "damageAOE": false,
            "block": 5,
            "ignoreBlock": false,
            "energy": 0,
        },
        "tooltip": 'Gain µ block',
    },

    "005": {
        "name": "focus energy",
        "type": "normal",
        "category": "ability",
        "rarity": "rare",
        "cost": 1,
        "target": false,
        "effect": {
            "draw": 0,
            "damage": 0,
            "damageAOE": false,
            "block": 0,
            "ignoreBlock": false,
            "energy": 2,
        },
        "tooltip": 'Gain 2 energy',
    },

    "006": {
        "name": "fury swipes",
        "type": "normal",
        "category": "attack",
        "rarity": "medium",
        "cost": 1,
        "target": true,
        "damageTimes": 3,
        "effect": {
            "draw": 0,
            "damage": 2,
            "damageAOE": false,
            "block": 0,
            "ignoreBlock": false,
            "energy": 0,
        },
        "tooltip": 'Deal <span class="damage-amount">§</span> damage to an ennemy 3 times',
    },

    "007": {
        "name": "calm mind",
        "type": "psychic",
        "category": "ability",
        "rarity": "medium",
        "cost": 1,
        "target": false,
        "effect": {
            "buffSelfAttack": 1,
            "buffSelfDefense": 1,
        },
        "tooltip": 'Raises your attack and defense by one',
    },

    "008": {
        "name": "recover",
        "type": "psychic",
        "category": "ability",
        "rarity": "medium",
        "cost": 1,
        "target": false,
        "effect":{
            "selfHeal": 50
        },
        "tooltip": 'Heals 50% of your hp',
    },
}